on:
  push:
  workflow_dispatch:

jobs:
  deploy_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash -
          apt-get install -y nodejs
      - run: npm i
      - run: wget https://dl.min.io/client/mc/release/linux-arm64/mc -O /tmp/mc
      - run: chmod +x /tmp/mc
      - run: /tmp/mc alias set minio http://minio-service.minio.svc.cluster.local:9000 ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}
      - run: /tmp/mc mirror $PWD/ minio/ptools-chlrkdtkatjd --exclude '.git/*' --exclude '.gitea/*' --overwrite

